name: uhi-cws-lausanne
channels:
  - conda-forge
  - bioconda
dependencies:
  - contextily=1.6.2
  - geopandas=1.0.1
  - ipykernel
  - numpy=2.2.4
  - pandas=2.2.3
  - papermill
  - pip
  - pip:
      - -e .
      - https://github.com/martibosch/meteora/archive/main.zip
      - swisstopopy=0.1.0
  - pdal=2.8.4
  - pre-commit
  - python=3.12
  - python-pdal=3.4.5
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - snakemake
  - spreg=1.8.2
  - xarray=2025.4.0
